version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf
  - epub

python:
  version: "3.10"
  system_packages: true
  install:
    - requirements: docs/requirements.txt
