version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"


python:
  install:
    - requirements: docs/requirements.txt
